# Generated by Django 3.0.8 on 2021-06-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='names',
            new_name='name',
        ),
    ]
